# -*- coding: utf-8 -*-
"""grammar_check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oPC0QGS5ibn3uwys-Yy1OGmnrEmzxB0W
"""

#!pip3 install torch==1.8.2+cu102 torchvision==0.9.2+cu102 torchaudio===0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html

#!pip install git+https://github.com/PrithivirajDamodaran/Gramformer.git

from gramformer import Gramformer

gf = Gramformer(models = 1, use_gpu=False) # 0=detector, 1=highlighter, 2=corrector, 3=all





def grammar_check(raw_text):
  result = ""
  splitted_raw = raw_text.split(". ")
  for raw_sentence in splitted_raw:
      result += gf.correct(raw_sentence).pop() + " "
  return result

#grammar_check(text)



#gf.correct("And now for something completely different interesting silent")
#gf.correct("And now I have fresh sweet apples bananas mangoes")

from difflib import SequenceMatcher


def similar(raw_text_str, result_str):
    return 100 - 100 * (SequenceMatcher(None, raw_text_str, result_str).ratio())

    
#similar("When I does something, It're always for your good.", "When I do something, it's always for your good")